name: repertoire
favicon: null
layout_spectrum: 0.75931
typography_spectrum: 0.35991
title: "A repository for things I'd like to share with you"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#27222a'
    - '#2a5b86'
    - '#ffb87c'
    - '#cd552c'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.6114576340187341
purpose: []
